# Generated by Django 4.0.1 on 2022-04-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail',
            field=models.TextField(default='Python'),
        ),
    ]
