# Generated by Django 4.0.1 on 2022-04-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
