# Generated by Django 4.0.1 on 2022-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(default='project_default.jpg', upload_to='project_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(default='project_default.jpg', upload_to='project_image'),
        ),
    ]
