# Generated by Django 4.0.1 on 2022-04-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github',
            field=models.TextField(default='Link to Github'),
        ),
    ]
