# Generated by Django 4.0.1 on 2022-04-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='github',
            field=models.TextField(default='https://github.com/kannanunni-js'),
        ),
    ]
