# Generated by Django 4.0.1 on 2022-04-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='github',
        ),
    ]
